config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  
  get 'profiles/show'
  get '/home', to: 'static_pages#home'
  get '/home_new', to: 'static_pages#home_new'
  get '/home_request', to: 'static_pages#home_request'
  get '/guide', to: 'static_pages#guide'
  get '/ranking_like', to: 'static_pages#ranking_like'
  get '/ranking', to: 'static_pages#ranking'
  resources :users
  get '/users/:id/last_month', to: 'users#last_month'
  get '/users/:id/like', to: 'users#like'
  resource :profiles
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 50}
  validates :prefecture, presence: true

  belongs_to :prefecture
  belongs_to :user

  has_many_attached :images
  has_many :comments, dependent: :destroy
  belongs_to :best_comment, foreign_key: :best_comment_id, class_name: 'Comment', optional: true 
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  acts_as_taggable
  is_impressionable counter_cache: true

  scope :sorted, -> { order(created_at: :desc) }
  scope :current_month, -> { where(created_at: Time.current.beginning_of_month..Time.current.end_of_month) }
  scope :last_month, -> { where('created_at < ?', Date.current.beginning_of_month)}
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :users
  has_many :posts
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :prefecture
  belongs_to :user1, foreign_key: :user1_id, class_name: 'User', optional: true 
  belongs_to :user2, foreign_key: :user2_id, class_name: 'User', optional: true 
  belongs_to :user3, foreign_key: :user3_id, class_name: 'User', optional: true 
end

app/models/ranking_like.rb
class RankingLike < ApplicationRecord
  belongs_to :prefecture
  belongs_to :user1, foreign_key: :user1_id, class_name: 'User', optional: true 
  belongs_to :user2, foreign_key: :user2_id, class_name: 'User', optional: true 
  belongs_to :user3, foreign_key: :user3_id, class_name: 'User', optional: true 
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :prefecture, presence: true

  belongs_to :prefecture
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         :lockable

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :prefecture_id])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :prefecture_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :create, :destroy]
  
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    p @post
    impressionist(@post, "some message", unique: [:session_hash])
    @comments = @post.comments.page(params[:page]).per(10)
    @like = Like.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to home_new_path(prefecture_id: @post.prefecture_id), notice: "タスク「#{@post.title}」を作成されました。"
    else
      render :new
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'BA was successfully updated.' 
    else
      render home_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
    end
    flash[:success] = "タスク「#{@post.title}」を削除しました。"
    redirect_back(fallback_location: root_path)
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :prefecture_id, :request_help, :tag_list, :best_comment_id, images: []) 
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @post = current_user.posts
  end

  def update
    if current_user.update(user_params)
      redirect_to home_path, notice: "プロフィールが更新されました。"
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:avatar)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    @posts = Post.order('impressions_count DESC').take(6)
    @tags = Post.tag_counts_on(:tags).most_used(5)
  end

  def guide
  end

  def home 
    @posts = Post.order('impressions_count DESC').page(params[:page]).per(20)
    @posts = @posts.where(prefecture_id: params[:prefecture_id]) if params[:prefecture_id].present? 
    @posts = @posts.where('title LIKE :keyword OR content LIKE :keyword', keyword: "%#{params[:keyword]}%") if params[:keyword].present?
    @posts = @posts.tagged_with(params[:tag]) if params[:tag].present?
    @prefecture = Prefecture.find(params[:prefecture_id]) if params[:prefecture_id].present? 
  end

  def home_new
    @posts = Post.sorted.page(params[:page]).per(20)
    @posts = @posts.where(prefecture_id: params[:prefecture_id]) if params[:prefecture_id].present? 
    @posts = @posts.where('title LIKE :keyword OR content LIKE :keyword', keyword: "%#{params[:keyword]}%") if params[:keyword].present?
    @posts = @posts.tagged_with(params[:tag]) if params[:tag].present?
    @prefecture = Prefecture.find(params[:prefecture_id]) if params[:prefecture_id].present? 
  end

  def home_request
    @posts = Post.where(request_help: true).page(params[:page]).per(20)
    @posts = @posts.where(prefecture_id: params[:prefecture_id]) if params[:prefecture_id].present? 
    @posts = @posts.where('title LIKE :keyword OR content LIKE :keyword', keyword: "%#{params[:keyword]}%") if params[:keyword].present?
    @posts = @posts.tagged_with(params[:tag]) if params[:tag].present?
    @prefecture = Prefecture.find(params[:prefecture_id]) if params[:prefecture_id].present? 
  end

  def ranking_like
    @ranking_likes = RankingLike.last(47)
  end

  def ranking
    @rankings = Ranking.last(47)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(20)
  end

  def last_month
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(20)
  end

  def like
    @user = User.find(params[:id])
    @post = @user.liked_posts.page(params[:page]).per(20)
  end

  #def mypage
    #redirect_to user_path(current_user)
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/show.html.slim
.auth_title
  h3
    | プロフィール画像の編集
.row
  .col-md-6.offset-md-3
    .auth_form
      = form_with model: current_user, url: profiles_path, local: true do |f|
        .field
          = f.label :avatar
          br
          = f.file_field :avatar
        .actions
          = f.submit "更新", class: "btn btn-success btn-block"


      .divider
      h6.line 以下、選択で変更できます

      .avatar_colorWrap
        h6 画像周りのカラー

      .avatar_crownWrap
        h6 画像周りの王冠

app/views/static_pages/_post.html.slim
- posts.each do |post|
  .border_post.py-2
    .avatarwrap.d-inline-block.align-top.mr-5
        - if post.user.avatar.attached?
          = link_to (image_tag post.user.avatar, class: "trim-image-to-circle-s"), user_path(post.user)
        - else
          = link_to (image_pack_tag 'default.png', class: "trim-image-to-circle-s"), user_path(post.user)
    .postwrap.d-inline-block
      .titlewrap.d-block
        = link_to post.title, post_path(post)
        = l post.created_at, format: :short
      .contentwrap
        = post.content
      .imageswrap
        - if post.images.attached?
          - post.images.each do |image|
            = image_tag image.variant(resize_to_fill: [150, 150])
      .sub-informationWrap.samll
        sapn コメント:
        sapn #{post.comments.count}件/
        span 参考になった:
        - if current_user.already_liked?(post)
          = link_to post_like_path(post, id: post.likes.ids), method: :delete do
            i class="fas fa-heart unlike-btn"
          span #{post.liked_users.count}人/
        - else
          = link_to post_likes_path(post), method: :post
            i class="far fa-heart like-btn"
          span #{post.liked_users.count}人/
        span タグ:
        - if post.tag_list.present?
          - post.tags.each do |tag|
            = link_to tag, home_path(tag: tag.name)
        - else
          span なし

app/views/static_pages/_search.html.slim
h6 簡易絞り込み検索
= form_with url: home_path, method: :get, local: true do |f| 
  .form-group
    = f.label :keyword, "検索文字"
    = f.text_field :keyword, class: "form-control"
  .form-group
    = f.label :tag, "タグ"
    = f.text_field :tag, class: "form-control"
  .d-grid.gap-2.mt-4  
    = f.submit '検索', class: 'btn btn-primary'

app/views/static_pages/home.html.slim
.auth_title
  - if params[:prefecture_id].present?
    h3 #{@prefecture.name}の災害情報
  - else 
    h3 全国の災害情報
.row
  aside.col-md-3
    .user_info
      = render partial: "users/userinfo"

    .search-functionWrap
      h6 簡易絞り込み検索
      = form_with url: home_path, method: :get, local: true do |f| 
        .form-group
          = f.label :keyword, "検索文字"
          = f.text_field :keyword, class: "form-control"
        .form-group
          = f.label :tag, "タグ"
          = f.text_field :tag, class: "form-control"
        = f.hidden_field :prefecture_id, value: params[:prefecture_id]
        .d-grid.gap-2.mt-4  
          = f.submit '検索', class: 'btn btn-primary'

  .col-md-9.recent_popular_post
    ul.nav.nav-tabs.nav-justified#myTab role="tablist"
      li.nav-item = link_to "みんなが見ているtopic", home_path(prefecture_id: params[:prefecture_id]), class: "nav-link home_backgroud_color active"
      li.nav-item = link_to "新着投稿", home_new_path(prefecture_id: params[:prefecture_id]), class: "nav-link new_backgroud_color"
      li.nav-item = link_to "お助け申請", home_request_path(prefecture_id: params[:prefecture_id]), class: "nav-link request_backgroud_color"
    .row.home_backgroud_color
      - if  user_signed_in?
        = render partial: "static_pages/post", locals: { posts: @posts }
      - else 
        = render partial: "static_pages/post_unlogin", locals: { posts: @posts }
    .paginationWrap          
      = paginate @posts

app/views/static_pages/home_new.html.slim
.auth_title
  - if params[:prefecture_id].present?
    h3 #{@prefecture.name}の災害情報
  - else 
    h3 全国の災害情報
.row
  aside.col-md-3
    .user_info
      = render partial: "users/userinfo"

    .search-functionWrap
      h6 簡易絞り込み検索
      = form_with url: home_new_path, method: :get, local: true do |f| 
        .form-group
          = f.label :keyword, "検索文字"
          = f.text_field :keyword, class: "form-control"
        .form-group
          = f.label :tag, "タグ"
          = f.text_field :tag, class: "form-control"
        = f.hidden_field :prefecture_id, value: params[:prefecture_id]
        .d-grid.gap-2.mt-4  
          = f.submit '検索', class: 'btn btn-primary'

  .col-md-9.recent_popular_post
    ul.nav.nav-tabs.nav-justified#myTab role="tablist"
      li.nav-item = link_to "みんなが見ているtopic", home_path(prefecture_id: params[:prefecture_id]), class: "nav-link home_backgroud_color"
      li.nav-item = link_to "新着投稿", home_new_path(prefecture_id: params[:prefecture_id]), class: "nav-link new_backgroud_color active"
      li.nav-item = link_to "お助け申請", home_request_path(prefecture_id: params[:prefecture_id]), class: "nav-link request_backgroud_color"
    .row.new_backgroud_color
      - if  user_signed_in?
        = render partial: "static_pages/post", locals: { posts: @posts }
      - else 
        = render partial: "static_pages/post_unlogin", locals: { posts: @posts }
    .paginationWrap          
      = paginate @posts

app/views/static_pages/top.html.slim
.headerWrap
  .row
    .col-md-1
    .headersummaryWrap.col-md-6
      .headersummary
        h1 ニッチ化災害SNS
        h6 エリアやタグを選択して、あなたの地域情報をチェックしよう。
        - if user_signed_in?
          = link_to "全国の情報", home_path, class: 'btn btn-primary'
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-primary'
        -else
          = link_to '新規登録', new_user_registration_path, class: 'btn btn-primary'
          = link_to 'ログイン', new_user_session_path, class: 'btn btn-primary' 
    .headerPicture.aside.col-md-4
      = image_pack_tag '日本地図.png'
.mainWrap
  .row
    .quick-searchWrap.mb-5.py-4
      = form_with url: home_path, method: :get, local: true do |f| 
        .form-inline.text-center
          h5.d-inline クイック検索　
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, { prompt: "県を選択してください" }, {class: "form-box"}
          = f.text_field :keyword, placeholder: "キーワード入力" , class: "form-size"
          = f.text_field :tag, placeholder: "タグ[例:地震、台風、火事]", class: "form-size"
          = f.submit '検索', class: 'btn btn-primary' 
    .col-md-9
      .search-parameters-area.mb-5
        h5.areaSelectTitle.text-decoration-underline エリアで検索
        ul.areaSelectList
          li.ruralButtonWrap
            dl
              dt 北海道・東北
              dd = link_to "北海道", home_path(prefecture_id: 1), class: "btn btn-outline-dark btn-size"
              dd = link_to "青森", home_path(prefecture_id: 2), class: "btn btn-outline-dark btn-size"
              dd = link_to "岩手", home_path(prefecture_id: 3), class: "btn btn-outline-dark btn-size"
              dd = link_to "宮城", home_path(prefecture_id: 4), class: "btn btn-outline-dark btn-size"
              dd = link_to "秋田", home_path(prefecture_id: 5), class: "btn btn-outline-dark btn-size"
              dd = link_to "山形", home_path(prefecture_id: 6), class: "btn btn-outline-dark btn-size"
              dd = link_to "福島", home_path(prefecture_id: 7), class: "btn btn-outline-dark btn-size"
          li.ruralButtonWrap
            dl
              dt 関東
              dd = link_to "茨城", home_path(prefecture_id: 8), class: "btn btn-outline-dark btn-size"
              dd = link_to "栃木", home_path(prefecture_id: 9), class: "btn btn-outline-dark btn-size"
              dd = link_to "群馬", home_path(prefecture_id: 10), class: "btn btn-outline-dark btn-size"
              dd = link_to "埼玉", home_path(prefecture_id: 11), class: "btn btn-outline-dark btn-size"
              dd = link_to "千葉", home_path(prefecture_id: 12), class: "btn btn-outline-dark btn-size"
              dd = link_to "東京", home_path(prefecture_id: 13), class: "btn btn-outline-dark btn-size"
              dd = link_to "神奈川", home_path(prefecture_id: 14), class: "btn btn-outline-dark btn-size"  
          li.ruralButtonWrap
            dl
              dt 北陸・甲信越
              dd = link_to "新潟", home_path(prefecture_id: 15), class: "btn btn-outline-dark btn-size"
              dd = link_to "富山", home_path(prefecture_id: 16), class: "btn btn-outline-dark btn-size"
              dd = link_to "石川", home_path(prefecture_id: 17), class: "btn btn-outline-dark btn-size" 
              dd = link_to "福井", home_path(prefecture_id: 18), class: "btn btn-outline-dark btn-size"
              dd = link_to "山梨", home_path(prefecture_id: 19), class: "btn btn-outline-dark btn-size"
              dd = link_to "長野", home_path(prefecture_id: 20), class: "btn btn-outline-dark btn-size"
          li.ruralButtonWrap
            dl
              dt 中部
              dd = link_to "岐阜", home_path(prefecture_id: 21), class: "btn btn-outline-dark btn-size"
              dd = link_to "静岡", home_path(prefecture_id: 22), class: "btn btn-outline-dark btn-size"
              dd = link_to "愛知", home_path(prefecture_id: 23), class: "btn btn-outline-dark btn-size"
              dd = link_to "三重", home_path(prefecture_id: 24), class: "btn btn-outline-dark btn-size"
          li.ruralButtonWrap
            dl
              dt 関西
              dd = link_to "滋賀", home_path(prefecture_id: 25), class: "btn btn-outline-dark btn-size"
              dd = link_to "京都", home_path(prefecture_id: 26), class: "btn btn-outline-dark btn-size"
              dd = link_to "大阪", home_path(prefecture_id: 27), class: "btn btn-outline-dark btn-size"
              dd = link_to "兵庫", home_path(prefecture_id: 28), class: "btn btn-outline-dark btn-size"
              dd = link_to "奈良", home_path(prefecture_id: 29), class: "btn btn-outline-dark btn-size"
              dd = link_to "和歌山", home_path(prefecture_id: 30), class: "btn btn-outline-dark btn-size"
          li.ruralButtonWrap
            dl
              dt 中国
              dd = link_to "鳥取", home_path(prefecture_id: 31), class: "btn btn-outline-dark btn-size"
              dd = link_to "島根", home_path(prefecture_id: 32), class: "btn btn-outline-dark btn-size"
              dd = link_to "岡山", home_path(prefecture_id: 33), class: "btn btn-outline-dark btn-size"
              dd = link_to "広島", home_path(prefecture_id: 34), class: "btn btn-outline-dark btn-size"
              dd = link_to "山口", home_path(prefecture_id: 35), class: "btn btn-outline-dark btn-size"
          li.ruralButtonWrap
            dl
              dt 四国
              dd = link_to "徳島", home_path(prefecture_id: 36), class: "btn btn-outline-dark btn-size"
              dd = link_to "香川", home_path(prefecture_id: 37), class: "btn btn-outline-dark btn-size" 
              dd = link_to "愛媛", home_path(prefecture_id: 38), class: "btn btn-outline-dark btn-size"
              dd = link_to "高知", home_path(prefecture_id: 39), class: "btn btn-outline-dark btn-size"
          li.ruralButtonWrap
            dl
              dt 九州・沖縄
              dd = link_to "福岡", home_path(prefecture_id: 40), class: "btn btn-outline-dark btn-size"
              dd = link_to "佐賀", home_path(prefecture_id: 41), class: "btn btn-outline-dark btn-size"
              dd = link_to "長崎", home_path(prefecture_id: 42), class: "btn btn-outline-dark btn-size"
              dd = link_to "熊本", home_path(prefecture_id: 43), class: "btn btn-outline-dark btn-size"
              dd = link_to "大分", home_path(prefecture_id: 44), class: "btn btn-outline-dark btn-size"
              dd = link_to "宮崎", home_path(prefecture_id: 45), class: "btn btn-outline-dark btn-size"
              dd = link_to "鹿児島", home_path(prefecture_id: 46), class: "btn btn-outline-dark btn-size"
              dd = link_to "沖縄", home_path(prefecture_id: 47), class: "btn btn-outline-dark btn-size"
      .search-parameters-tag.mb-5
        h5.tagSelectTitle.text-decoration-underline タグで検索
        .tag-Wrap
          .tag-group.d-inline-block
            = link_to (image_pack_tag '地震.png', class: "trim-image-to-circle-l"), home_path(tag: "地震") 
            p 地震
            = link_to "津波", home_path(tag: "津波"), class: "btn btn-primary"
            = link_to "倒壊", home_path(tag: "倒壊"), class: "btn btn-primary"
          .tag-group.d-inline-block
            = link_to (image_pack_tag '火事.png', class: "trim-image-to-circle-l"), home_path(tag: "火事") 
            p 火事
            = link_to "煙", home_path(tag: "煙"), class: "btn btn-primary"
            = link_to "地区", home_path(tag: "地区"), class: "btn btn-primary"
          .tag-group.d-inline-block
            = link_to (image_pack_tag '台風.png', class: "trim-image-to-circle-l"), home_path(tag: "台風") 
            p 台風
            = link_to "風速", home_path(tag: "風速"), class: "btn btn-primary"
            = link_to "暴風", home_path(tag: "暴風"), class: "btn btn-primary"
          .tag-group.d-inline-block
            = link_to (image_pack_tag '豪雪・豪雨.png', class: "trim-image-to-circle-l"), home_path(tag: "豪雪・豪雨") 
            p 豪雪・豪雨
            = link_to "積雪", home_path(tag: "積雪"), class: "btn btn-primary"
            = link_to "凍結", home_path(tag: "凍結"), class: "btn btn-primary"
          .tag-group.d-inline-block
            = link_to (image_pack_tag '事件.png', class: "trim-image-to-circle-l"), home_path(tag: "事件") 
            p 事件
            = link_to "殺人", home_path(tag: "殺人"), class: "btn btn-primary"
            = link_to "盗難", home_path(tag: "盗難"), class: "btn btn-primary"
      .featured-topicWrap.mb-5
        h5.text-decoration-underline 全国で注目のtopic
        #carouselExampleControls.carousel.slide data-ride="carousel"
          .carousel-inner.font-small
            .home_backgroud_color.m-3
              .carousel-item.active
                - @posts.first(1).each do |post|
                  .row
                    .col-md-1.offset-md-2
                      aside.avatarwrap
                        - if post.user.avatar.attached?
                          = image_tag post.user.avatar, class: "trim-image-to-circle-s"
                        - else
                          = image_pack_tag 'default.png', class: "trim-image-to-circle-s"
                    .col-md-8
                      .postwrap
                        .titlewrap.d-block
                          = link_to post.title, post_path(post)
                          = l post.created_at, format: :short
                        .contentwrap
                          = post.content
                        .imageswrap
                          - if post.images.attached?
                            - post.images.each do |image|
                              = image_tag image.variant(resize_to_fill: [150, 150])
                        .sub-informationWrap
                          small コメント：
                          sapn #{post.comments.count}件
                          small 参考になった：
                          small タグ： 
                          - if post.tag_list.present?
                            - post.tags.each do |tag|
                              = link_to tag, home_path(tag: tag.name)
                          - else
                            span タグはありません
                          small 閲覧数：
                          = post.impressionist_count
              - @posts.drop(1).each do |post|
                .carousel-item   
                  .row    
                    .col-md-1.offset-md-2
                      aside.avatarwrap
                        - if post.user.avatar.attached?
                          = image_tag post.user.avatar, class: "trim-image-to-circle-s"
                        - else
                          = image_pack_tag 'default.png', class: "trim-image-to-circle-s"
                    .col-md-8
                      .postwrap
                        .titlewrap.d-block
                          = link_to post.title, post_path(post)
                          = l post.created_at, format: :short
                        .contentwrap
                          = post.content
                        .sub-informationWrap
                          small コメント：
                          sapn #{post.comments.count}件
                          small 参考になった：
                          small タグ： 
                          - if post.tag_list.present?
                            - post.tags.each do |tag|
                              = link_to tag, home_path(tag: tag.name)
                          - else
                            span タグはありません
                          small 閲覧数：
                          = post.impressionist_count  
          a.carousel-control-prev href="#carouselExampleControls" role="button" data-slide="prev"
            span.carousel-control-prev-icon aria-hidden="true"
            span.sr-only Previous
          a.carousel-control-next href="#carouselExampleControls" role="button" data-slide="next"
            span.carousel-control-next-icon aria-hidden="true"
            span.sr-only Next

    .aside-Wrap.col-md-3
      .popularTagWrap.borderBottom
        h6 話題のタグで検索
        ul
          - if @tags.present?
            - @tags.each do |tag|
              li= link_to "#{tag.name}(#{tag.taggings_count})", home_path(tag: tag.name)
          - else
            p 登録されているタグはありません
      .linkWrap.borderBottom
        h6 リンク
        ul
          li = link_to "ランクについて", ranking_like_path, class: "d-block"
          li = link_to "災害小ネタ(特集)(未開設)", "#", class: "d-block"
          li = link_to "お問い合わせ(未開設)", "#", class: "d-block"
          li = link_to "利用規約(未開設)", "#", class: "d-block"
          li = link_to "アプリを作った経緯(未開設)", "#", class: "d-block"
          li = link_to "登録情報の変更", edit_user_registration_path, class: "d-block"
          li = link_to "退会する(未開設)", "#", class: "d-block"
      .smallstoryWrap.borderBottom
        h6  災害小ネタ(特集)
        ul
          li = link_to "地震で閉じ込められたら?(未開設)", "#", class: "d-block"
          li = link_to "災害時必須アイテム(未開設)", "#", class: "d-block"
          li = link_to "災害時必須アイテム(未開設)", "#", class: "d-block"
          li = link_to "災害時必須アイテム(未開設)", "#", class: "d-block"
          li = link_to "特集一覧へ▶︎(未開設)", "#", class: "d-block"
      .rankingWrap.borderBottom
        h6  今月のお役立ち君/お助け君
        ul
          li  〇〇
          li  〇〇
          li  〇〇


 