config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  
  get 'profiles/show'
  get '/home', to: 'static_pages#home'
  get '/home_new', to: 'static_pages#home_new'
  get '/home_request', to: 'static_pages#home_request'
  get '/guide', to: 'static_pages#guide'
  get '/ranking_like', to: 'static_pages#ranking_like'
  get '/ranking', to: 'static_pages#ranking'
  resources :users
  get '/users/:id/last_month', to: 'users#last_month'
  get '/users/:id/like', to: 'users#like'
  resource :profiles
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :prefecture, presence: true

  belongs_to :prefecture
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         :lockable

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  #before_action :configure_sign_up_params, only: [:create]
  #before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_sign_up_params
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  #end

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_account_update_params
    #devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  #end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    home_path(prefecture_id: current_user.prefecture_id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   home_path(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_sign_in_params
    #devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  #end

  def after_sign_in_path_for(resource)
    home_path(prefecture_id: current_user.prefecture_id)
  end 
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(20)
  end

  def last_month
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(20)
  end

  def like
    @user = User.find(params[:id])
    @post = @user.liked_posts.page(params[:page]).per(20)
  end

  #def mypage
    #redirect_to user_path(current_user)
  #end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.slim
- if user_signed_in?
  - if current_user.avatar.attached?
    = link_to (image_tag current_user.avatar, class: "trim-image-to-circle-l"), user_path(current_user)
  - else
    = link_to (image_pack_tag 'default.png', class: "trim-image-to-circle-l"), user_path(current_user)
  h6 = current_user.name
  = link_to '投稿する', new_post_path, class: 'btn btn-primary d-grid gap-2'
  = link_to 'マイページはこちら▶︎', user_path(current_user), class: 'd-block small'
  = link_to 'プロフィールの編集▶︎', profiles_path, class: 'd-block small'
- else
  = image_pack_tag 'default.png', class: "trim-image-to-circle-l"
  h6 ゲスト

app/views/users/edit.html.slim
.auth_title
  section
    h2
      | プロフィール画像の編集
.row
  .col-md-6.offset-md-3
    .auth_form
      = form_with model: current_user, url: users_path, local: true do |f|
        .field
          = f.label :avatar
          br
          = f.file_field :avatar
        .actions
          = f.submit "更新", class: "btn btn-success btn-block"


      .divider
      h6.line 以下、選択で変更できます

      .avatar_colorWrap
        h6 画像周りのカラー

      .avatar_crownWrap
        h6 画像周りの王冠

app/views/users/last_month.html.slim
.auth_title
  - if user_signed_in? && current_user.id.to_s == params[:id]
    h3
      | マイページ
  - else
    h3
      | #{@user.name}さん
.row
  aside.col-md-3
    .user_info
      - if @user.avatar.attached?
        = image_tag @user.avatar, class: "trim-image-to-circle-l"
      - else
        = image_pack_tag 'default.png', class: "trim-image-to-circle-l"
      h6 = @user.name
      - if user_signed_in? && current_user.id.to_s == params[:id]
        = link_to '投稿する', new_post_path, class: 'btn btn-primary d-grid gap-2'
        = link_to 'マイページはこちら▶︎', user_path(current_user), class: 'd-block small'
        = link_to 'プロフィールの編集▶︎', profiles_path, class: 'd-block small'
      
    .search-functionWrap
      h6 表示選択
      ul
        li = link_to "今月の投稿", user_path(params[:id])
        li = link_to "先月以前の投稿", controller: "users", action: "last_month"
        li = link_to "いいねしている投稿", controller: "users", action: "like"

      
  .col-md-9.recent_popular_post
    h5 先月以前の投稿
    .row
      - @post.last_month.sorted.each do |post|
        .col-md-2.border_post
          .avatarwrap.col-md-3
            - if post.user.avatar.attached?
              = image_tag post.user.avatar, class: "trim-image-to-circle-s"
            - else
              = image_pack_tag 'default.png', class: "trim-image-to-circle-s"

        .col-md-10.border_post
          .postwrap
            .titlewrap.d-block
              = link_to post.title, post_path(post)
              = l post.created_at, format: :short
              - if post.user_id == current_user.id
                = link_to "削除", post_path(post), method: :delete, data: { confirm: "投稿「#{post.title}」を削除します。よろしいですか？" }
            .contentwrap
              = post.content
            .imageswrap
              - if post.images.attached?
                - post.images.each do |image|
                  = image_tag image.variant(resize_to_fill: [150, 150])
            .sub-informationWrap
              small コメント：
              small 参考になった：
              small タグ：
              - if post.tag_list.present?
                - post.tags.each do |tag|
                  = link_to tag, home_path(tag: tag.name)
              - else
                span タグはありません
      .paginationWrap          
        = paginate @post

app/views/users/like.html.slim
.auth_title
  - if user_signed_in? && current_user.id.to_s == params[:id]
    h3
      | マイページ
  - else
    h3
      | #{@user.name}さん
.row
  aside.col-md-3
    .user_info
      - if @user.avatar.attached?
        = image_tag @user.avatar, class: "trim-image-to-circle-l"
      - else
        = image_pack_tag 'default.png', class: "trim-image-to-circle-l"
      h6 = @user.name
      - if user_signed_in? && current_user.id.to_s == params[:id]
        = link_to '投稿する', new_post_path, class: 'btn btn-primary d-grid gap-2'
        = link_to 'マイページはこちら▶︎', user_path(current_user), class: 'd-block small'
        = link_to 'プロフィールの編集▶︎', profiles_path, class: 'd-block small'
      
    .search-functionWrap
      h6 表示選択
      ul
        li = link_to "今月の投稿", user_path(params[:id])
        li = link_to "先月以前の投稿", controller: "users", action: "last_month"
        li = link_to "いいねしている投稿", controller: "users", action: "like"

      
  .col-md-9.recent_popular_post
    h5 いいねしている投稿
    .row
      - @post.each do |post|
        .col-md-2.border_post
          .avatarwrap.col-md-3
            - if post.user.avatar.attached?
              = image_tag post.user.avatar, class: "trim-image-to-circle-s"
            - else
              = image_pack_tag 'default.png', class: "trim-image-to-circle-s"

        .col-md-10.border_post
          .postwrap
            .titlewrap.d-block
              = link_to post.title, post_path(post)
              = l post.created_at, format: :short
              - if post.user_id == current_user.id
                = link_to "削除", post_path(post), method: :delete, data: { confirm: "投稿「#{post.title}」を削除します。よろしいですか？" }
            .contentwrap
              = post.content
            .imageswrap
              - if post.images.attached?
                - post.images.each do |image|
                  = image_tag image.variant(resize_to_fill: [150, 150])
            .sub-informationWrap
              small コメント：
              small 参考になった：
              small タグ：
              - if post.tag_list.present?
                - post.tags.each do |tag|
                  = link_to tag, home_path(tag: tag.name)
              - else
                span タグはありません
      .paginationWrap          
        = paginate @post

app/views/users/show.html copy.slim
.auth_title
  section
    - if user_signed_in? && current_user.id.to_s == params[:id]
      h3
        | マイページ
    - else
      h3
        | 他人ページ
.row
  aside.col-md-3
    section.user_info
      - if current_user.avatar.attached?
        = image_tag current_user.avatar, class: "trim-image-to-circle-l"
      - else
        = image_pack_tag 'default.png', class: "trim-image-to-circle-l"
      h6 = current_user.name
      = link_to 'プロフィールの変更▶︎', profiles_path, class: 'd-block'
      = link_to '投稿する', new_post_path, class: 'btn btn-primary d-grid gap-2'
      
    .search-functionWrap
      h6 表示選択
      ul
        li = link_to "今月の投稿", "#"
        li = link_to "先月以前の投稿", "#"
        li = link_to "いいねしている投稿", "#"

      
  .col-md-9.recent_popular_post
    h5 今月の投稿
    .row
      - @post.current_month.sorted.each do |post|
        .col-md-2.border_post
          aside.avatarwrap.col-md-3
            - if post.user.avatar.attached?
              = image_tag post.user.avatar, class: "trim-image-to-circle-s"
            - else
              = image_pack_tag 'default.png', class: "trim-image-to-circle-s"
        .col-md-10.border_post
          .postwrap
            .titlewrap.d-block
              = link_to post.title, post_path(post)
              = l post.created_at, format: :short
              = link_to "削除", post_path(post), method: :delete, data: { confirm: "投稿「#{post.title}」を削除します。よろしいですか？" }
            .contentwrap
              = post.content
            .imageswrap
              - if post.images.attached?
                - post.images.each do |image|
                  = image_tag image.variant(resize_to_fill: [150, 150])
    h5 先月以前の投稿
    .row
      - @post.last_month.sorted.each do |post|
        .col-md-2.border_post
          aside.avatarwrap.col-md-3
            - if post.user.avatar.attached?
              = image_tag post.user.avatar, class: "trim-image-to-circle-s"
            - else
              = image_tag 'default.png', class: "trim-image-to-circle^s"

        .col-md-10.border_post
          .postwrap
            .titlewrap.d-block
              = link_to post.title, post_path(post)
              = l post.created_at, format: :short
              = link_to "削除", post_path(post), method: :delete, data: { confirm: "投稿「#{post.title}」を削除します。よろしいですか？" }
            .contentwrap
              = post.content
            .imageswrap
              - if post.images.attached?
                - post.images.each do |image|
                  = image_tag image.variant(resize_to_fill: [150, 150])
            .sub-informationWrap
              small コメント：
              small 参考になった：
              small タグ：
              - if post.tag_list.present?
                - post.tags.each do |tag|
                  = link_to tag, home_path(tag: tag.name)
              - else
                span タグはありません
    h5 いいねしている投稿
    .row
      - @user.liked_posts.each do |post|
        .col-md-2.border_post
          aside.avatarwrap.col-md-3
            - if post.user.avatar.attached?
              = image_tag post.user.avatar, class: "trim-image-to-circle-s"
            - else
              = image_pack_tag 'default.png', class: "trim-image-to-circle-s"

        .col-md-10.border_post
          .postwrap
            .titlewrap.d-block
              = link_to post.title, post_path(post)
              = l post.created_at, format: :short
              = link_to "削除", post_path(post), method: :delete, data: { confirm: "投稿「#{post.title}」を削除します。よろしいですか？" }
            .contentwrap
              = post.content
            .imageswrap
              - if post.images.attached?
                - post.images.each do |image|
                  = image_tag image.variant(resize_to_fill: [150, 150])
            .sub-informationWrap
              small コメント：
              small 参考になった：
              small タグ：
              - if post.tag_list.present?
                - post.tags.each do |tag|
                  = link_to tag, home_path(tag: tag.name)
              - else
                span タグはありません

app/views/users/show.html.slim
.auth_title
  - if user_signed_in? && current_user.id.to_s == params[:id]
    h3
      | マイページ
  - else
    h3
      | #{@user.name}さん
.row
  aside.col-md-3
    .user_info
      - if @user.avatar.attached?
        = image_tag @user.avatar, class: "trim-image-to-circle-l"
      - else
        = image_pack_tag 'default.png', class: "trim-image-to-circle-l"
      h6 = @user.name
      - if user_signed_in? && current_user.id.to_s == params[:id]
        = link_to '投稿する', new_post_path, class: 'btn btn-primary d-grid gap-2'
        = link_to 'マイページはこちら▶︎', user_path(current_user), class: 'd-block small'
        = link_to 'プロフィールの編集▶︎', profiles_path, class: 'd-block small'
      
    .search-functionWrap
      h6 表示選択
      ul
        li = link_to "今月の投稿", user_path(params[:id])
        li = link_to "先月以前の投稿", controller: "users", action: "last_month"
        li = link_to "いいねしている投稿", controller: "users", action: "like"

      
  .col-md-9.recent_popular_post
    h5 今月の投稿
    .row
      - @post.current_month.sorted.each do |post|
        .col-md-2.border_post
          .avatarwrap.col-md-3
            - if post.user.avatar.attached?
              = image_tag post.user.avatar, class: "trim-image-to-circle-s"
            - else
              = image_pack_tag 'default.png', class: "trim-image-to-circle-s"
        .col-md-10.border_post
          .postwrap
            .titlewrap.d-block
              = link_to post.title, post_path(post)
              = l post.created_at, format: :short
              - if post.user_id == current_user.id
                = link_to "削除", post_path(post), method: :delete, data: { confirm: "投稿「#{post.title}」を削除します。よろしいですか？" }
            .contentwrap
              = post.content
            .imageswrap
              - if post.images.attached?
                - post.images.each do |image|
                  = image_tag image.variant(resize_to_fill: [150, 150])
      .paginationWrap          
        = paginate @post