config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  
  get 'profiles/show'
  get '/home', to: 'static_pages#home'
  get '/home_new', to: 'static_pages#home_new'
  get '/home_request', to: 'static_pages#home_request'
  get '/guide', to: 'static_pages#guide'
  get '/ranking_like', to: 'static_pages#ranking_like'
  get '/ranking', to: 'static_pages#ranking'
  resources :users
  get '/users/:id/last_month', to: 'users#last_month'
  get '/users/:id/like', to: 'users#like'
  resource :profiles
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 50}
  validates :prefecture, presence: true

  belongs_to :prefecture
  belongs_to :user

  has_many_attached :images
  has_many :comments, dependent: :destroy
  belongs_to :best_comment, foreign_key: :best_comment_id, class_name: 'Comment', optional: true 
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  acts_as_taggable
  is_impressionable counter_cache: true

  scope :sorted, -> { order(created_at: :desc) }
  scope :current_month, -> { where(created_at: Time.current.beginning_of_month..Time.current.end_of_month) }
  scope :last_month, -> { where('created_at < ?', Date.current.beginning_of_month)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :create, :destroy]
  
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    p @post
    impressionist(@post, "some message", unique: [:session_hash])
    @comments = @post.comments.page(params[:page]).per(10)
    @like = Like.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to home_new_path(prefecture_id: @post.prefecture_id), notice: "タスク「#{@post.title}」を作成されました。"
    else
      render :new
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'BA was successfully updated.' 
    else
      render home_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
    end
    flash[:success] = "タスク「#{@post.title}」を削除しました。"
    redirect_back(fallback_location: root_path)
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :prefecture_id, :request_help, :tag_list, :best_comment_id, images: []) 
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/new.html.slim
.auth_title
  section
    h3
      | 新規投稿
.row
  .col-md-6.offset-md-3
    .auth_form
      = form_with model: @post, local: true do |f|
        = render "shared/error_messages", object: f.object
        .field.mb-3
          = f.label :title
          = f.text_field :title, class: "form-control"
        .field.mb-3
          = f.label :content
          = f.text_area :content, class: "form-control"
        .field.mb-3
          = f.label :prefecture_id, "都道府県"
          br
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, selected: current_user.prefecture_id
        .field.mb-3
          = f.label :images, "画像"
          br
          = f.file_field :images, multiple: true
        .field.mb-3
          = f.label :tag_list, "タグ"
          = f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control"
        .field.mb-3
          = f.label :request_help, "お助け申請"
          br
          = f.check_box :request_help, {}, checked_value = "true", unchecked_value = "false"
        .actions
          = f.submit "投稿", class: "btn btn-success btn-block"

app/views/posts/show.html.slim
.auth_title
  h3 投稿詳細
.row
  aside.col-md-3
    .user_info
      = render partial: "users/userinfo"
    .commentWrap
      h6 コメントする
      - if user_signed_in?
        = form_with(model: [@post, Comment.new], url: post_comments_path(@post), local: true) do |f|
          .form-group
            = f.text_area :content, class: "form-control", rows: 5
          .d-grid.gap-2.mt-4 
            =f.submit 'コメントする', class: "btn btn-primary"
  .col-md-9.recent_popular_post
    .main-postwrap.border_post
      .row
        h6.text-decoration-underline 投稿内容
        .col-md-10.py-3
          .avatarwrap.d-inline-block.align-top.mr-5
            - if @post.user.avatar.attached?
              = link_to (image_tag @post.user.avatar, class: "trim-image-to-circle-s"), user_path(@post.user)
            - else
              = link_to (image_pack_tag 'default.png', class: "trim-image-to-circle-s"), user_path(@post.user)
          .postwrap.d-inline-block
            .titlewrap.d-block
              = @post.title
              = l @post.created_at, format: :short
            .contentwrap
              = @post.content
            .imageswrap
              - if @post.images.attached?
                - @post.images.each do |image|
                  = image_tag image.variant(resize_to_fill: [150, 150])
            .sub-informationWrap.small
              span コメント:
              sapn #{@post.comments.count}件/
              span 参考になった:
              - if current_user.already_liked?(@post)
                = link_to post_like_path(@post), method: :delete do
                  i class="fas fa-heart unlike-btn"
                span #{@post.liked_users.count}人/
              - else
                = link_to post_likes_path(@post), method: :post
                  i class="far fa-heart like-btn"
                span #{@post.liked_users.count}人/
              span タグ:
              - if @post.tag_list.present?
                - @post.tags.each do |tag|
                  span #{tag}/
              - else
                span なし
              span 閲覧数:
              span #{@post.impressionist_count}
    .reply-postwrap
      .row.home_backgroud_color
        h6.text-decoration-underline コメント一覧
        - if @comments
          - @comments.each do |comment|
            .col-md-10.border_post.py-3 class="#{ "best-comment" if @post.best_comment_id == comment.id }"
              .avatarwrap.d-inline-block.align-top.mr-5
                - if comment.user && comment.user.avatar.attached?
                  = link_to (image_tag comment.user.avatar, class: "trim-image-to-circle-s"), user_path(comment.user)
                - else
                  = link_to (image_pack_tag 'default.png', class: "trim-image-to-circle-s"), user_path(comment.user)
              .postwrap.d-inline-block
                .contentwrap
                  - if comment.user
                    = link_to comment.user.name, user_path(comment.user.id), class: "d-block"
                  = comment.content
            .col-md-2.d-flex.align-items-center
              - if @post.user_id == current_user.id
                - unless @post.user_id == comment.user_id
                  - unless @post.best_comment_id.present? 
                    = form_with(model: @post, local: true, data: {confirm: "#{comment.user.name}さんの回答をベストアンサーにします。この修正は変更できませんが、よろしいですか？"}) do |form|
                      = form.hidden_field :best_comment_id, value: comment.id
                      .actions
                        = form.submit 'BAにする', class: "btn btn-secondary", disabled: @post.best_comment_id.present? 
                
        .paginationWrap          
          = paginate @comments