config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  
  get 'profiles/show'
  get '/home', to: 'static_pages#home'
  get '/home_new', to: 'static_pages#home_new'
  get '/home_request', to: 'static_pages#home_request'
  get '/guide', to: 'static_pages#guide'
  get '/ranking_like', to: 'static_pages#ranking_like'
  get '/ranking', to: 'static_pages#ranking'
  resources :users
  get '/users/:id/last_month', to: 'users#last_month'
  get '/users/:id/like', to: 'users#like'
  resource :profiles
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 50}
  validates :prefecture, presence: true

  belongs_to :prefecture
  belongs_to :user

  has_many_attached :images
  has_many :comments, dependent: :destroy
  belongs_to :best_comment, foreign_key: :best_comment_id, class_name: 'Comment', optional: true 
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  acts_as_taggable
  is_impressionable counter_cache: true

  scope :sorted, -> { order(created_at: :desc) }
  scope :current_month, -> { where(created_at: Time.current.beginning_of_month..Time.current.end_of_month) }
  scope :last_month, -> { where('created_at < ?', Date.current.beginning_of_month)}
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :users
  has_many :posts
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :prefecture
  belongs_to :user1, foreign_key: :user1_id, class_name: 'User', optional: true 
  belongs_to :user2, foreign_key: :user2_id, class_name: 'User', optional: true 
  belongs_to :user3, foreign_key: :user3_id, class_name: 'User', optional: true 
end

app/models/ranking_like.rb
class RankingLike < ApplicationRecord
  belongs_to :prefecture
  belongs_to :user1, foreign_key: :user1_id, class_name: 'User', optional: true 
  belongs_to :user2, foreign_key: :user2_id, class_name: 'User', optional: true 
  belongs_to :user3, foreign_key: :user3_id, class_name: 'User', optional: true 
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :prefecture, presence: true

  belongs_to :prefecture
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         :lockable

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :create, :destroy]
  
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    p @post
    impressionist(@post, "some message", unique: [:session_hash])
    @comments = @post.comments.page(params[:page]).per(10)
    @like = Like.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to home_new_path(prefecture_id: @post.prefecture_id), notice: "タスク「#{@post.title}」を作成されました。"
    else
      render :new
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'BA was successfully updated.' 
    else
      render home_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
    end
    flash[:success] = "タスク「#{@post.title}」を削除しました。"
    redirect_back(fallback_location: root_path)
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :prefecture_id, :request_help, :tag_list, :best_comment_id, images: []) 
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @post = current_user.posts
  end

  def update
    if current_user.update(user_params)
      redirect_to home_path, notice: "プロフィールが更新されました。"
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(20)
  end

  def last_month
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(20)
  end

  def like
    @user = User.find(params[:id])
    @post = @user.liked_posts.page(params[:page]).per(20)
  end

  #def mypage
    #redirect_to user_path(current_user)
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DisasterSharing
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"
  body
    header.navbar.navbar-dark.bg-dark.navbar-fixed-top
      .container
        = link_to "災害情報アプリ", root_path, class: "text-light"
        ul.nav
          li.nav-item = link_to "ニッチ化災害SNSとは", guide_path, class: "text-light nav-link"
          li.nav-item = link_to "トップ", root_path, class: "text-light nav-link"
          - if user_signed_in?
            li.nav-item = link_to "マイページ", user_path(current_user), class: "text-light nav-link"
            li.nav-item = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-light nav-link"
          - else
            li.nav-item = link_to "新規登録", new_user_registration_path, class: "text-light nav-link"
            li.nav-item = link_to "ログイン", new_user_session_path, class: "text-light nav-link"
    .container
      - if flash.notice.present?
        .alert.alert-success=flash.notice      
      = yield
      footer
        footer-bookmark
          footer-title.float-left
            h6 災害情報アプリ
          footer-bookmark-list.small.float-right
            ul.d-inline-block.list-unstyled
              li.nav-item = link_to "お問い合わせ", "#", class: "nav-link"
              li.nav-item = link_to "ランクについて", ranking_path, class: "nav-link"
              li.nav-item = link_to "災害特集", "#", class: "nav-link"
            ul.d-inline-block.list-unstyled
              li.nav-item = link_to "注意事項", "#", class: "nav-link"
              li.nav-item = link_to "製作者の体験談", "#", class: "nav-link"
              li.nav-item = link_to "全国のトピック", "#", class: "nav-link"
            ul.d-inline-block.list-unstyled
              li.nav-item = link_to "注意事項", "#", class: "nav-link"
              li.nav-item = link_to "製作者の体験談", "#", class: "nav-link"
              li.nav-item = link_to "全国のトピック", "#", class: "nav-link"

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      フォームに <%= object.errors.count %>つのエラーが含まれています。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/top/index.html.slim
.headerWrap.row
  .col-md-1
  .headersummaryWrap.col-md-6
    .headersummary
      h1 ニッチ化災害SNS
      h6 エリアやタグを選択して、あなたの地域情報をチェックしよう。
      = link_to '新規登録', new_user_registration_path, class: 'btn btn-primary'
      = link_to 'ログイン', new_user_session_path, class: 'btn btn-primary' 
  .headerPicture.aside.col-md-4
    = image_tag '日本地図.png'
.featured-topicWrap